### ISSUE TITLE
Привет тут не видно

### ISSUE THREAD

**Issue by jokys-dev** [jAba65/jAba-Discord-Theme#1]
Не видно при навидении на то где кто то _напис_ал исравте пожалуста но оформление красиво МОЖНО СТАВИТ СВОЙ КАРТИНА!!
![скриншот](https://github.com/jAba65/jAba-Discord-Theme/assets/172440637/2f982d4f-5ec4-4570-9333-bac749f9b638)

**Comment by jAba65** [comment]
Здравствуйте, сделал так что бы было красиво и видно

**Comment by jAba65** [comment]
Done
